### ISSUE TITLE
Remove logform and Winston from call stacks

### ISSUE THREAD

**Issue by terrisgit** [good-ware/js-log#68]
Example:

   at Format.transform (/app/node_modules/logform/combine.js:20:24)\n    at DerivedLogger._transform (/app/node_modules/winston/lib/winston/logger.js:313:29)\n    at DerivedLogger.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)\n    at DerivedLogger.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)\n    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)\n    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)\n    at DerivedLogger.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)\n    at DerivedLogger.log (/app/node_modules/winston/lib/winston/logger.js:216:12)\n    at ExceptionHandler._uncaughtException (/app/node_modules/winston/lib/winston/exception-handler.js:220:17)\n

**Comment by dev-guy** [comment]
Implemented in v9.0.0
